version: '3'

services:
  database:
    image: postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      - POSTGRES_DB=gobarber
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
    volumes:
      - ./docker/database:/var/lib/postgresql/data
    networks:
      - backend

  api:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: gobarber-api
    volumes:
      - .:/api
    depends_on:
      - database
    restart: unless-stopped
    networks:
      - backend
    ports:
      - "3333:3333"
    links:
      - database

networks:
  backend:
    driver: bridge
